language: node_js

node_js: 
  - "10"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install: 
  - export TZ='Asia/Shanghai'

install: 
  - yarn global add vuepress

script:
  - yarn docs:build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/.vuepress/dist
  name: $GIT_NAME
  email: $GIT_EMAIL
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
